### ISSUE TITLE
02-first-model Task list

### ISSUE THREAD

**Issue by LeeDayday** [LeeDayday/money-mentor#4]
### 최종 목표
- [x] 설문조사 결과 저장
- [x] 결과를 open ai api와 함께 보내기

### 할 일
- [x] 설문지 json으로 (question, 선택지 json)
- [x] front 구현 
    - [x] 버튼 정상 작동 
- [x] back 구현 
    - [x] custom  ID 생성 
    - [x] question 결과 잘 담기 
    - [x] 결과를 DB에 저장 

- [ ] test code 작성
